language: node_js
node_js:
      - 8
cache:
      directories:
            - node_modules
script:
      - yarn test
      - yarn build
deploy:
      provider: heroku
      api_key:
            secure: "0a01819a-cfae-4c2d-ba3b-b388714a4939"